name: Run E2E Tests

on: [pull_request]

jobs: 
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest

        services:
           postgress:
                image: bitnami/postgresql:latest
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USERNAME: docker
                    POSTGRES_PASSWORD: docker
                    POSTGRES_DATABASE: apisolid


        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '23.10.0'
                  cache: 'npm'
            - run: npm ci

            - name: Run E2E tests
              run: npm run test:e2e
              env:
                JWT_SECRET: supersecretkey
                DATABASE_URL: postgresql://docker:docker@localhost:5432/api_solid_test?schema=public
                NODE_ENV: test